config/routes.rb
TinyVault::Application.routes.draw do
  namespace :admin do
    resources :footer_links do
      collection do
        post :sort
      end
    end
    resources :accounts
    resources :users
  end
  
  match 'admin', :to => 'admin#index', :via => :get
  
  resources :accounts do
    member do
      post :switch
    end
    resources :sites do
      resources :keys do
        resources :group_keys
      end
    end
    
    resources :groups do
      resources :memberships
    end
    resources :user_accounts
  end
  
  match 'keys/fill', :via => :get
  
  resources :key_imports
  
  resources :sites
  resources :keys do
    collection do
      post :edit_multiple
      put :update_multiple
    end
  end
  resources :groups
  
  resources :users
  resources :password_resets
  resource :settings
  
  match 'login', :to => 'user_sessions#new', :via => :get
  match 'login', :to => 'user_sessions#create', :via => :post
  match 'logout', :to => 'user_sessions#destroy', :via => :delete
  
  root :to => "start#index", :via => :get
end

app/models/account.rb
class Account < ActiveRecord::Base
  validates_presence_of :name
  
  has_many :user_accounts
  has_many :users, :through => :user_accounts
  
  has_many :sites
  has_many :keys, :through => :sites
  has_many :groups
  
  has_many :key_imports
  
  scope :ordered_by_name, :order => 'name ASC'
  
  def self.from_param!(param)
    find(param)
  end
  
  def user_accounts_with_users
    # RAILS BUG: This does not work here ... :order => 'users.full_name ASC')
    user_accounts.find(:all, :include => :user)
  end

  def self.paginate_for_list(filter, options = {})
    with_search_scope(filter) do
      paginate(options.merge(:order => 'accounts.name ASC'))
    end
  end
  
protected
  def self.with_search_scope(filter, &block)
    conditions = filter.empty? ? nil : ['accounts.name LIKE ?', "%#{filter.query}%"]
    with_scope :find => { :conditions => conditions } do
      yield
    end
  end
end

app/models/role/account/admin.rb
module Role::Account::Admin
  include Role::Base
  
  def method_missing(method)
    if method.to_s =~ /^can_.*\?$/
      true
    else
      super
    end
  end
end

app/models/role/account/observer.rb
module Role::Account::Observer
  include Role::Base
  
  def method_missing(method)
    if method.to_s =~ /^can_.*\?$/
      false
    else
      super
    end
  end
end

app/models/role/account/user.rb
module Role::Account::User
  include Role::Base
  
  allow :create_sites, :edit_sites, :delete_sites,
        :create_keys, :edit_keys, :delete_keys
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_filter :login_required
  before_filter :can_see_account_details!
  
  def index
    @accounts = current_user.accounts.ordered_by_name
  end
  
  def new
    @account = Account.new
  end
  
  def show
    @account = Account.find(params[:id])
    can_see_account!(@account)
  end
  
  def edit
    @account = Account.find(params[:id])
    can_edit_account!(@account)
  end
  
  def create
    @account = Account.new(params[:account])
    if @account.save
      current_user.accounts << @account
      current_user.set_role_for_account(@account, 'admin')
      current_user.switch_to_account @account
      flash[:notice] = I18n.t('flash.notice.created_account', :account => @account.name)
      redirect_to root_path
    else
      render :action => 'new'
    end
  end
  
  def update
    @account = Account.find(params[:id])
    can_edit_account!(@account) do
      if @account.update_attributes(params[:account])
        flash[:notice] = I18n.t('flash.notice.updated_account', :account => @account.name)
        redirect_to account_path(@account)
      else
        render :action => 'edit'
      end
    end
  end
  
  def switch
    @account = Account.find(params[:id])
    can_switch_to_account!(@account) do
      current_user.switch_to_account(@account)
      flash[:notice] = I18n.t('flash.notice.switched_account', :account => @account.name)
      redirect_to root_path
    end
  end
end

app/controllers/admin/accounts_controller.rb
class Admin::AccountsController < ApplicationController
  before_filter :login_required
  before_filter :can_see_all_accounts!
  before_filter :can_edit_all_accounts!, :only => [ :edit, :update ]
  
  def index
    @search_filter = SearchFilter.new(params[:search_filter])
    @accounts = Account.paginate_for_list(@search_filter, :page => params[:page])
    render :update do |page|
      page.replace_html 'accounts', :partial => 'index'
    end if request.xhr?
  end
  
  def show
    @account = Account.find(params[:id])
  end
  
  def edit
    @account = Account.find(params[:id])
  end
  
  def update
    @account = Account.find(params[:id])
    if @account.update_attributes(params[:account])
      flash[:notice] = I18n.t("flash.notice.updated_account", :account => @account.name)
      redirect_to admin_accounts_path
    else
      render :action => 'edit'
    end
  end
end

app/views/admin/accounts/_index.html.erb
<%= will_paginate @accounts %>

<table class="list">
  <thead>
    <tr>
      <th><%= t('.name') %></th>
      <th><%= t('.users') %></th>
      <th><%= t('.options') %></th>
    </tr>
  </thead>
  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= link_to highlight(account.name, @search_filter.query), admin_account_path(account) %></td>
        <td><%= account.users.count %></td>
        <td><%= link_to 'Edit', edit_admin_account_path(account) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @accounts %>

app/views/admin/accounts/_tabs.html.erb
<%= tabs(:selected => selected) do |t| %>
  <% t.tab :information, t(".information"), admin_account_path(@account) %>
  <% t.tab :edit, t(".edit"), edit_admin_account_path(@account) %>
<% end %>

app/views/admin/accounts/edit.html.erb
<h2><%= t('.edit_account') %></h2>

<%= render :partial => "tabs", :locals => { :selected => :edit } %>

<%= form_for [:admin, @account], :html => { :class => 'form' } do |f| %>
  <%= f.error_messages :header_message => t('.could_not_update_account') %>
  
  <p class="form_item">
    <span class="label"><%= f.label :name, t('.name'), :class => 'required' %></span>
    <%= f.text_field :name %>
  </p>
  
  <p><%= f.submit t('.save_account') %></p>
<% end %>

app/views/admin/accounts/index.html.erb
<h2><%= t('.all_accounts') %></h2>

<% if @accounts.empty? %>
  <p><%= t('.no_accounts') %></p>
<% else %>
  <%= render :partial => "/shared/filter", :locals => { :url => admin_accounts_path } %>
  
  <div id="accounts">
    <%= render :partial => "index" %>
  </div>
<% end %>

app/views/admin/accounts/show.html.erb
<h2><%= t('.account', :account => @account.name) %></h2>

<%= render :partial => "tabs", :locals => { :selected => :information } %>

<%= render :partial => "/accounts/info" %>

<h3><%= t(".users") %></h3>

<% if @account.users.empty? %>
  <p><%= t('.no_users') %></p>
<% else %>
  <ul class="asterisk">
    <% @account.users.each do |user| %>
      <li><%= link_to user.full_name, user_path(user) %> (<%= t("account.role.#{user.user_account_for(@account).role}") %>)</li>
    <% end %>
  </ul>
<% end %>