config/routes.rb
TinyVault::Application.routes.draw do
  namespace :admin do
    resources :footer_links do
      collection do
        post :sort
      end
    end
    resources :accounts
    resources :users
  end
  
  match 'admin', :to => 'admin#index', :via => :get
  
  resources :accounts do
    member do
      post :switch
    end
    resources :sites do
      resources :keys do
        resources :group_keys
      end
    end
    
    resources :groups do
      resources :memberships
    end
    resources :user_accounts
  end
  
  match 'keys/fill', :via => :get
  
  resources :key_imports
  
  resources :sites
  resources :keys do
    collection do
      post :edit_multiple
      put :update_multiple
    end
  end
  resources :groups
  
  resources :users
  resources :password_resets
  resource :settings
  
  match 'login', :to => 'user_sessions#new', :via => :get
  match 'login', :to => 'user_sessions#create', :via => :post
  match 'logout', :to => 'user_sessions#destroy', :via => :delete
  
  root :to => "start#index", :via => :get
end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :account
  
  has_many :memberships
  has_many :members, :through => :memberships, :class_name => 'User', :source => :user
  
  has_many :group_keys
  has_many :keys, :through => :group_keys

  validates_presence_of :name
  has_permalink :name

  def to_param
    permalink
  end
  
  def self.from_param!(param)
    find_by_permalink!(param)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :login_required
  before_filter :find_account
  active_tab :groups

  def index
    @groups = @account.groups
  end

  def new
    can_create_groups!(@account) do
      @group = @account.groups.build
    end
  end
  
  def create
    can_create_groups!(@account) do
      @group = @account.groups.build(params[:group])
      if @group.save
        flash[:notice] = I18n.t('flash.notice.created_group', :group => @group.name)
        redirect_to account_group_path(@account, @group)
      else
        render :action => 'new'
      end
    end
  end
  
  def show
    @group = @account.groups.find_by_permalink!(params[:id])
  end
  
  def edit
    can_edit_groups!(@account) do
      @group = @account.groups.find_by_permalink!(params[:id])
    end
  end
  
  def update
    can_edit_groups!(@account) do
      @group = @account.groups.find_by_permalink!(params[:id])
      if @group.update_attributes(params[:group])
        flash[:notice] = I18n.t('flash.notice.updated_group', :group => @group.name)
        redirect_to account_group_path(@account, @group)
      else
        render :action => 'edit'
      end
    end
  end
  
  def destroy
    can_delete_groups!(@account) do
      @group = @account.groups.find_by_permalink!(params[:id])
      @group.destroy
      flash[:notice] = I18n.t('flash.notice.deleted_group', :group => @group.name)
      redirect_to groups_path
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for [@account, @group], :html => { :class => 'form' } do |f| %>
  <%= f.error_messages :header_message => t('.could_not_create_group') %>
  
  <p class="form_item">
    <span class="label"><%= f.label :name, t('.name'), :class => 'required' %></span>
    <%= f.text_field :name %>
  </p>

  <p><%= f.submit t('.save_group') %></p>
<% end %>

app/views/groups/edit.html.erb
<h2><%= t('.edit_group', :group => @group.name) %></h2>

<%= render :partial => "form" %>

app/views/groups/index.html.erb
<h2><%= t('.all_groups') %></h2>

<% if @groups.empty? %>
  <p><%= t('.no_groups_configured') %></p>
<% else %>
  <% if @groups.empty? %>
    <p><%= t('.no_groups_found') %></p>
  <% else %>
    <table class="list">
      <thead>
        <tr>
          <th><%= t('.name') %></th>
          <th><%= t('.members') %></th>
          <% if current_user.can_edit_groups?(@account) %>
            <th><%= t('.options') %></th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @groups.each do |group| %>
          <tr>
            <td><%= link_to group.name, account_group_path(group.account, group) %></td>
            <td><%= group.members.count %></td>
            <td>
              <%= action_list do |a| %>
                <% if current_user.can_edit_groups?(@account) %>
                  <% a.link_to t('.edit'), edit_account_group_path(group.account, group) %>
                  <% a.link_to t('.delete'), account_group_path(group.account, group), :method => :delete, :confirm => t('.confirm_delete') if current_user.can_delete_groups?(@account) %>
                <% end %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
<% end %>

<% if current_user.can_create_groups?(@account) %>
  <p><%= link_to t('.new_group'), new_account_group_path(@account) %></p>
<% end %>

app/views/groups/new.html.erb
<h2><%= t('.new_group') %></h2>

<%= render :partial => "form" %>

app/views/groups/show.html.erb
<h2><%= t('.group', :group => @group.name) %></h2>

<p><%= t('.members') %></p>

<table class="list">
  <thead>
    <tr>
      <th><%= t('.name') %></th>
      <% if current_user.can_edit_groups?(@account) %>
        <th><%= t('.options') %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @group.memberships.each do |membership| %>
      <tr>
        <td><%= link_to membership.user.name, user_path(membership.user) %></td>
        <td>
          <%= action_list do |a| %>
            <% if current_user.can_edit_groups?(@account) %>
              <% a.link_to t('.delete'), account_group_membership_path(@account, @group, membership), :method => :delete, :confirm => t('.confirm_delete') if current_user.can_remove_user_from_group?(membership.user, @group) %>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if current_user.can_add_user_to_group?(@group) %>
  <%= form_for [@account, @group, Membership.new], :html => { :class => 'form' } do |f| %>
    <p class="form_item">
      <span class="label"><%= f.label :user_id, t('.name'), :class => 'required' %></span>
      <%= f.select :user_id, @account.users.collect { |user| [user.full_name, user.id] } %>
    </p>

    <p><%= f.submit t('.add') %></p>
  <% end %>
<% end %>

<% if current_user.can_edit_groups?(@account) %>
  <p><%= link_to t(".edit_group"), edit_account_group_path(@account, @group) %></p>
<% end %>