config/routes.rb
TinyVault::Application.routes.draw do
  namespace :admin do
    resources :footer_links do
      collection do
        post :sort
      end
    end
    resources :accounts
    resources :users
  end
  
  match 'admin', :to => 'admin#index', :via => :get
  
  resources :accounts do
    member do
      post :switch
    end
    resources :sites do
      resources :keys do
        resources :group_keys
      end
    end
    
    resources :groups do
      resources :memberships
    end
    resources :user_accounts
  end
  
  match 'keys/fill', :via => :get
  
  resources :key_imports
  
  resources :sites
  resources :keys do
    collection do
      post :edit_multiple
      put :update_multiple
    end
  end
  resources :groups
  
  resources :users
  resources :password_resets
  resource :settings
  
  match 'login', :to => 'user_sessions#new', :via => :get
  match 'login', :to => 'user_sessions#create', :via => :post
  match 'logout', :to => 'user_sessions#destroy', :via => :delete
  
  root :to => "start#index", :via => :get
end

app/models/footer_link.rb
class FooterLink < ActiveRecord::Base
  validates_presence_of :text, :url
  
  acts_as_list
  
  scope :ordered, :order => 'position ASC'
end

app/controllers/admin/footer_links_controller.rb
class Admin::FooterLinksController < ApplicationController
  before_filter :login_required
  before_filter :can_edit_footer_links!
  
  def index
    @footer_links = FooterLink.ordered
  end
  
  def new
    @footer_link = FooterLink.new
  end
  
  def edit
    @footer_link = FooterLink.find(params[:id])
  end
  
  def create
    @footer_link = FooterLink.new(params[:footer_link])
    if @footer_link.save
      flash[:notice] = I18n.t("flash.notice.created_footer_link")
      redirect_to admin_footer_links_path
    else
      render :action => 'new'
    end
  end
  
  def update
    @footer_link = FooterLink.find(params[:id])
    if @footer_link.update_attributes(params[:footer_link])
      flash[:notice] = I18n.t("flash.notice.updated_footer_link")
      redirect_to admin_footer_links_path
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @footer_link = FooterLink.find(params[:id])
    @footer_link.destroy
    flash[:notice] = I18n.t("flash.notice.removed_footer_link")
    redirect_to admin_footer_links_path
  end
  
  def sort
    params[:link].each_with_index do |id, i|
      FooterLink.find(id).update_attribute(:position, i)
    end
    render :nothing => true
  end
end

app/views/admin/footer_links/_form.html.erb
<%= form_for [:admin, @footer_link], :html => { :class => 'form' } do |f| %>
  <%= f.error_messages :header_message => t('.could_not_create_footer_link') %>
  
  <p class="form_item">
    <span class="label"><%= f.label :text, t('.text') %></span>
    <%= f.text_field :text %>
  </p>

  <p class="form_item">
    <span class="label"><%= f.label :url, t('.url') %></span>
    <%= f.text_field :url %>
  </p>
  
  <p><%= f.submit t('.save_footer_link') %></p>
<% end %>

app/views/admin/footer_links/edit.html.erb
<h2><%= t('.edit_footer_link') %></h2>

<%= render :partial => "form" %>

app/views/admin/footer_links/index.html.erb
<h2><%= t('.footer_links') %></h2>

<% if @footer_links.empty? %>
  <p><%= t('.nothing_found') %></p>
<% else %>
  <table class="list">
    <thead>
      <tr>
        <th>&nbsp;</th>
        <th><%= t('.name') %></th>
        <th><%= t('.url') %></th>
        <th><%= t('.options') %></th>
      </tr>
    </thead>
    <tbody id="links">
      <% @footer_links.each do |footer_link| %>
        <tr id="order_<%= footer_link.id %>">
          <td class="handle" title="<%= t('.drag_to_sort') %>">&nbsp;&#x2195;&nbsp;</td>
          <td><%= footer_link.text %></td>
          <td><%= link_to footer_link.url, footer_link.url %></td>
          <td>
            <%= link_to t('.edit'), edit_admin_footer_link_path(footer_link) %> |
            <%= link_to t('.remove'), admin_footer_link_path(footer_link), :method => :delete, :confirm => t('.really_remove_footer_link') %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<%= javascript_tag %{
  Sortable.create('links', {
    tag: 'tr',
    scroll: window,
    handle: 'handle',
    onUpdate: function() { new Ajax.Request('#{sort_admin_footer_links_path}?authenticity_token=#{form_authenticity_token}', { method: "post", parameters: Sortable.serialize("links", { name: 'link' }) }); }
  });
} %>

<p><%= link_to t('.new_footer_link'), new_admin_footer_link_path %></p>

app/views/admin/footer_links/new.html.erb
<h2><%= t('.new_footer_link') %></h2>

<%= render :partial => "form" %>