config/routes.rb
TinyVault::Application.routes.draw do
  namespace :admin do
    resources :footer_links do
      collection do
        post :sort
      end
    end
    resources :accounts
    resources :users
  end
  
  match 'admin', :to => 'admin#index', :via => :get
  
  resources :accounts do
    member do
      post :switch
    end
    resources :sites do
      resources :keys do
        resources :group_keys
      end
    end
    
    resources :groups do
      resources :memberships
    end
    resources :user_accounts
  end
  
  match 'keys/fill', :via => :get
  
  resources :key_imports
  
  resources :sites
  resources :keys do
    collection do
      post :edit_multiple
      put :update_multiple
    end
  end
  resources :groups
  
  resources :users
  resources :password_resets
  resource :settings
  
  match 'login', :to => 'user_sessions#new', :via => :get
  match 'login', :to => 'user_sessions#create', :via => :post
  match 'logout', :to => 'user_sessions#destroy', :via => :delete
  
  root :to => "start#index", :via => :get
end

app/models/key_import.rb
class KeyImport < ActiveRecord::Base
  class Row
    attr_reader :site_name, :site_description, :home_url, :login_url, :description, :username, :password
    
    def initialize(csv_row)
      @site_name, @site_description, @home_url, @login_url, @description, @username, @password = *csv_row
    end
    
    def create!(key_import)
      site = Site.find_or_create_by_account_id_and_name(:account_id => key_import.account.id, :name => @site_name, :description => @site_description, :home_url => @home_url, :login_url => @login_url)
      site.keys.create(:key_import => key_import, :user => key_import.user, :description => @description, :username => @username, :password => @password)
    end
  end
  
  belongs_to :account
  belongs_to :user
  
  has_many :keys, :dependent => :destroy
  
  after_create :import
  
  def self.fields
    [
      I18n.t("key_import.fields.site_name"),
      I18n.t("key_import.fields.site_description"),
      I18n.t("key_import.fields.home_url"),
      I18n.t("key_import.fields.login_url"),
      I18n.t("key_import.fields.description"),
      I18n.t("key_import.fields.username"),
      I18n.t("key_import.fields.password")
    ]
  end
  
  def self.from_param!(param)
    find(param)
  end
  
  def rows
    @rows ||= FasterCSV.parse(csv_data).collect { |row| Row.new(row) }
  end
  
  def import
    rows.each { |row| row.create!(self) }
  end
end

app/controllers/key_imports_controller.rb
class KeyImportsController < ApplicationController
  before_filter :login_required
  before_filter :find_account
  before_filter :can_import_keys!
  
  def index
    @key_imports = @account.key_imports
  end
  
  def new
    @key_import = @account.key_imports.build
  end
  
  def create
    @key_import = @account.key_imports.build(params[:key_import])
    @key_import.user = current_user
    if params[:commit] == I18n.t("key_imports.form.preview")
      @preview = true
      render :action => 'new'
    else
      @key_import.save
      redirect_to key_import_path(@key_import)
    end
  end
  
  def show
    @key_import = @account.key_imports.find(params[:id])
    @search_filter = SearchFilter.new
  end
  
  def destroy
    @key_import = @account.key_imports.find(params[:id])
    @key_import.destroy
    redirect_to key_imports_path
  end
end

app/views/key_imports/_form.html.erb
<%= f.error_messages :header_message => t('.could_not_import') %>

<p class="form_item">
  <span class="label"><%= f.label :description, t('.description') %></span>
  <%= f.text_field :description %>
</p>

<p class="form_item">
  <span class="label"><%= f.label :csv_data, t('.csv_data'), :class => 'required' %></span>
  <%= f.text_area :csv_data, :cols => 80, :style => 'font-family: "Courier New", Courier, monospace' %>
</p>

<p>
  <%= f.submit t('.preview') %>
  <%= f.submit t(".import") if @preview %>
</p>

app/views/key_imports/_preview.html.erb
<h3><%= t(".preview") %></h3>

<table class="list">
  <thead>
    <tr>
      <% KeyImport.fields.each do |field| %>
        <th><%= field %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @key_import.rows.each do |row| %>
      <tr>
        <td><%= row.site_name %></td>
        <td><%= row.site_description %></td>
        <td><%= row.home_url %></td>
        <td><%= row.login_url %></td>
        <td><%= row.description %></td>
        <td><%= row.username %></td>
        <td><%= row.password %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/key_imports/index.html.erb
<h2><%= t(".imports_for_account", :account => @account.name) %></h2>

<% if @key_imports.empty? %>
  <p><%= t(".nothing_found") %></p>
<% else %>
  <table class="list">
    <thead>
      <tr>
        <th><%= t(".when") %></th>
        <th><%= t(".who") %></th>
        <th><%= t(".description") %></th>
        <th><%= t(".options") %></th>
      </tr>
    </thead>
    <tbody>
      <% @key_imports.each do |key_import| %>
        <tr>
          <td><%= link_to t(".imported_at", :time => time_ago_in_words(key_import.created_at)), key_import_path(key_import) %></td>
          <td><%= link_to key_import.user.full_name, user_path(key_import.user) %></td>
          <td><%= link_to key_import.description, key_import_path(key_import) unless key_import.description.blank? %></td>
          <td><%= link_to t('.delete'), key_import_path(key_import), :method => :delete, :confirm => t(".really_delete_import") %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<p>
  <%= link_to t(".new_import"), new_key_import_path %>
</p>

app/views/key_imports/new.html.erb
<h2><%= t(".new_import") %></h2>

<p><%= t(".instructions") %></p>

<p><%= t(".field_names", :fields => KeyImport.fields.join(', ')) %></p>

<%= render :partial => 'preview' if @preview %>

<% form_for [@key_import], :html => { :class => 'form' } do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
<% end %>

app/views/key_imports/show.html.erb
<h2><%= t(".keys_for_import") %></h2>

<p><%= @key_import.description %></p>

<%= render :partial => "/keys/list", :locals => { :keys => @key_import.keys } %>